"""
HTML report generation.

Renders a ScanResult + ScoreResult into a single, self-contained
HTML file (inline CSS, no external dependencies) using Jinja2.
"""

from __future__ import annotations

from pathlib import Path

from jinja2 import Template

from sentinel.engine.findings import ScanResult
from sentinel.engine.scoring import ScoreResult

_TEMPLATE = Template("""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>CloudOps Sentinel — Scan Report</title>
<style>
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 40px; }
  .container { max-width: 900px; margin: 0 auto; }
  h1 { color: #58a6ff; margin-bottom: 4px; }
  .subtitle { color: #8b949e; margin-bottom: 24px; }
  .meta { color: #8b949e; font-size: 14px; margin-bottom: 32px; }
  .score-card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 24px; margin-bottom: 32px; display: flex; align-items: center; gap: 32px; }
  .score-value { font-size: 48px; font-weight: bold; }
  .score-pass { color: #3fb950; }
  .score-warning { color: #d29922; }
  .score-fail { color: #f85149; }
  .status-badge { padding: 6px 16px; border-radius: 20px; font-weight: bold; font-size: 14px; display: inline-block; }
  .badge-pass { background: #1a3d24; color: #3fb950; }
  .badge-warning { background: #3d3319; color: #d29922; }
  .badge-fail { background: #3d1a1a; color: #f85149; }
  table.summary { width: 100%; border-collapse: collapse; margin-bottom: 32px; }
  table.summary th, table.summary td { text-align: left; padding: 10px 16px; border-bottom: 1px solid #30363d; }
  .sev-CRITICAL { color: #f85149; font-weight: bold; }
  .sev-HIGH { color: #f0883e; font-weight: bold; }
  .sev-MEDIUM { color: #d29922; }
  .sev-LOW { color: #58a6ff; }
  .sev-INFO { color: #8b949e; }
  .finding { background: #161b22; border: 1px solid #30363d; border-left: 4px solid #f85149; border-radius: 6px; padding: 16px 20px; margin-bottom: 16px; }
  .finding.HIGH { border-left-color: #f0883e; }
  .finding.MEDIUM { border-left-color: #d29922; }
  .finding.LOW { border-left-color: #58a6ff; }
  .finding.INFO { border-left-color: #8b949e; }
  .finding-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }
  .finding-title { font-weight: bold; font-size: 16px; }
  .finding-id { color: #8b949e; font-size: 13px; font-family: monospace; }
  .finding-desc { color: #c9d1d9; margin-bottom: 8px; }
  .finding-recommendation { color: #8b949e; font-size: 14px; }
  .finding-recommendation strong { color: #c9d1d9; }
  footer { color: #8b949e; font-size: 12px; margin-top: 40px; text-align: center; }
</style>
</head>
<body>
<div class="container">
  <h1>CloudOps Sentinel</h1>
  <div class="subtitle">AWS Security & Compliance Report</div>
  <div class="meta">
    Region: {{ scan.region }} &middot;
    Scanned: {{ scan.scan_started_at }} &middot;
    Duration: {{ scan.scan_duration_seconds }}s &middot;
    Services: {{ scan.services_scanned | join(", ") }}
  </div>

  <div class="score-card">
    <div class="score-value score-{{ status_class }}">{{ score.score }}/100</div>
    <div>
      <div class="status-badge badge-{{ status_class }}">{{ score.status }}</div>
      <div style="margin-top: 8px; color: #8b949e; font-size: 13px;">
        This is a project-defined risk score, not an official AWS or industry rating.
      </div>
    </div>
  </div>

  <table class="summary">
    <tr><th>Severity</th><th>Count</th></tr>
    {% for severity, count in score.severity_counts.items() %}
    <tr><td class="sev-{{ severity }}">{{ severity }}</td><td>{{ count }}</td></tr>
    {% endfor %}
  </table>

  <h2>Findings ({{ scan.findings | length }})</h2>
  {% for f in scan.findings %}
  <div class="finding {{ f.severity }}">
    <div class="finding-header">
      <span class="finding-title">{{ f.title }}</span>
      <span class="finding-id">{{ f.finding_id }} &middot; {{ f.severity }}</span>
    </div>
    <div class="finding-desc">{{ f.description }}</div>
    <div class="finding-recommendation"><strong>Recommendation:</strong> {{ f.recommendation }}</div>
  </div>
  {% else %}
  <p>No findings — nothing to report.</p>
  {% endfor %}

  <footer>Generated by CloudOps Sentinel &middot; Score methodology documented in README</footer>
</div>
</body>
</html>
""")


def write_html_report(scan_result: ScanResult, score_result: ScoreResult, output_path: str) -> str:
    """
    Render the report to disk as a self-contained HTML file.
    Returns the absolute path written to.
    """
    status_class_map = {"PASS": "pass", "WARNING": "warning", "FAIL": "fail"}
    status_class = status_class_map.get(score_result.status, "fail")

    html = _TEMPLATE.render(
        scan=scan_result.to_dict(),
        score=score_result.model_dump(),
        status_class=status_class,
    )

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

    return str(path.resolve())